name: guldly
description: Buy & Sell Physical Gold
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.2.0

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Backend
  supabase_flutter: ^2.3.4

  # Networking
  http: ^1.2.1

  # UI
  google_fonts: ^6.2.1

  # Storage
  shared_preferences: ^2.2.3

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true